# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df5db09cbd76272ba538f50d7cdce813416abf14572b6b67aeb64e78689717d95278b1cb0b22ae53ed9aa15dfc2f97d853d11c4d655253dd676060b67abbc369

test:
  secret_key_base: 5afac4c41c521d137d87df17e1614deaa196fd5616f94d8b6dcbd5fc6a972fc8968445379b2b1b7aa9156942c55f254d918cd9ca09cd3fe674cbbe4032c0e2c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
